version: '3.1'
services:
  db:
    image: mysql:8.0.23
    container_name: shopperDB
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33065:3306
  backend:
    container_name: backend
    build: ./backend
    image: node:16
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=shopper
      - DB_USER=root
      - DB_PASSWORD=123456
      - SERVER_PORT=3001
    volumes:
      - ./:/usr/app
    working_dir: /usr/app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - db